-- Create the keep-alive table for Supabase pause prevention
-- Run this script in your Supabase SQL editor

CREATE TABLE IF NOT EXISTS "keep-alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NULL DEFAULT '',
  random UUID NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert some placeholder data
INSERT INTO "keep-alive" (name) VALUES 
  ('placeholder'),
  ('example')
ON CONFLICT DO NOTHING;

-- Create an index for better performance
CREATE INDEX IF NOT EXISTS idx_keep_alive_name ON "keep-alive" (name);

-- Optional: Create a function to clean up old records (runs automatically)
CREATE OR REPLACE FUNCTION cleanup_keep_alive()
RETURNS void AS $$
BEGIN
  -- Delete records older than 24 hours
  DELETE FROM "keep-alive" 
  WHERE created_at < NOW() - INTERVAL '24 hours';
END;
$$ LANGUAGE plpgsql;

-- Optional: Set up a cron job to run cleanup (requires pg_cron extension)
-- Uncomment the following lines if you have pg_cron enabled in your Supabase project
-- SELECT cron.schedule('cleanup-keep-alive', '0 2 * * *', 'SELECT cleanup_keep_alive();'); 