date: '2021'
category: literatura-expandida
tech:
  - React
  - Nes.CSS
links:
  live: https://mc-txt.netlify.app/
  github: https://mc-txt.netlify.app/
images:
  - src: /images/mc-txt.png
status: published
